---
apiVersion: apps/v1
kind: Deployment 
metadata:
    name: fb-deploy
    labels:
        app: facebook
spec:
    replicas: 1
    selector:
        matchLabels:
            app: facebook
    template:
        metadata:
            name: fbpod
            labels:
                app: facebook
        spec:
            nodeName: ip-192-168-7-120.ec2.internal
            containers:
                - name: fbcont1
                  image: nginx
