---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: fb-deploy
    labels:
        app: facebook
spec:
    replicas: 2
    selector:
        matchLabels:
            app: facebook
    template:
        metadata:
            name: fb-pod
            labels:
                app: facebook
        spec:
            nodeSelector:
                env: prod
            containers:
                - name: fb-cont1
                  image: nginx

