---
apiVersion: v1 
kind: Pod 
metadata:
    name: db-pod
    labels:
        app: database
spec:
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                        - key: env
                          operator: In 
                          values:
                              - prod
                             
            preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                      matchExpressions:
                          - key: topology.kubernetes.io/zone
                            operator: In 
                            values:
                                - us-east-1b
    tolerations:
        - key: "critical"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    containers:
        - name: dbcont1
          image: postgres:latest