---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ebs-static
spec:
    storageClassName: "" # empty string must be explicitly set otherwise default storageclass
    volumeName: ebs-static
    accessModes: 
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi