---
apiVersion: v1
kind: Pod
metadata:
    name: ebs-static-pod
    labels:
        purpose: ebs-static
spec:
    nodeSelector:
        topology.kubernetes.io/zone: us-east-1c
    containers:
        - name: facebook
          image: nginx
          volumeMounts:
              - name: ebs-static
                mountPath: /usr/share/nginx/html
    volumes:
        - name: ebs-static
          persistentVolumeClaim:
            claimName: ebs-static

---
apiVersion: v1 
kind: Service
metadata:
    name: fb-srv
spec:
    type: LoadBalancer
    selector:
        purpose: ebs-static
    ports:
        - port: 80
          targetPort: 80