---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: efs-static
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 5Gi
    storageClassName: ""
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
    csi:
        driver: efs.csi.aws.com
        volumeHandle: fs-022b028cf12280b9a  #copy filesystem id