---
apiVersion: v1
kind: Pod
metadata:
    name: pod-secret
spec:
    containers:
        - name: secret-cont
          image: nginx
          envFrom:
              - secretRef:
                    name: pod-secret