---
apiVersion: v1
kind: Pod
metadata:
    name: pod-configmap
spec:
    containers:
        - name: ex-pod-cont
          image: nginx
          envFrom:
              - configMapRef:
                    name: nginx-config-map