---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: fb-deploy
    labels:
        app: facebook
        env: lab
spec:
    selector:
        matchLabels:
            app: facebook
    replicas: 3
    template:
        metadata:
            name: fb-pod
            labels:
                app: facebook
                version: VC_V2
        spec:
            containers:
                - name: fb-cont1
                  image: devopshubg333/batch15d:python_flaskapp
                  ports:
                      - containerPort: 8080