---
apiVersion: v1
kind: Pod
metadata: 
    name: fbpod
    namespace: fb-namespace
    labels: 
        app: facebook
        env: lab
spec: 
    containers:
      - name: fbcont1
        image: devopshubg333/batch15d:mcfbapp