my_list = [1,2,3,5,4,7,3,2,1]
print(my_list, type(my_list))
my_list.append(5)
print("After append: ", my_list)
my_list.extend([6,8,9])
print("After extend: ", my_list)
my_list.insert(0,0)
print("After insert: ", my_list)
popped_element = my_list.pop()
print("Popped element: ", popped_element)
print("After Pop: ", my_list)
index_of_1 = my_list.index(1)
print("index_of_1: ", index_of_1)
my_list.sort()
print("After sort: ", my_list)
my_list.reverse()
print("After reverse: ", my_list)
print("length of list: ", len(my_list))
print("maximum element: ", max(my_list))
print("minimum element: ", min(my_list))
print("count of 3: ", my_list.count(3))
my_list.remove(6)
print("After remove: ", my_list)
copied_list = my_list.copy()
print("copied list: ", copied_list)
my_list.clear()
print("After clear: ", my_list)

print(type(my_list))
